-- MySQL Script generated by MySQL Workbench
-- Sun Sep 26 12:57:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema utpnotas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema utpnotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `utpnotas` DEFAULT CHARACTER SET utf8 ;
USE `utpnotas` ;

-- -----------------------------------------------------
-- Table `utpnotas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpnotas`.`users` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NULL,
  `fullname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `create_date` DATETIME NULL DEFAULT now(),
  `status` VARCHAR(20) NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `utpnotas`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpnotas`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL,
  `title` VARCHAR(100) NULL,
  `text` VARCHAR(1000) NULL,
  `create_date` DATETIME NULL DEFAULT now(),
  `update_date` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `FK_USERS_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `FK_USERS`
    FOREIGN KEY (`username`)
    REFERENCES `utpnotas`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
